### PR TITLE
Move create invite to classroom's General setting

### PR DESCRIPTION
**Pull request by MonitorIizard**
#59 

- rename folder from `classrooom` (triple o) => `classroom`
- move `create invite` component to general setting
- in skeleton change from static array `[1, 2, 3, 4]` => `Array.from({length})`, so when we need more skeleton just change length.
- in login feature ( I should create new issue. ). Make error message blink, so when user key wrong password again. They will see the `error message`  it blink.
- In `create invite code` remove `drawer`.
- And set `general` group can't de-select.

[Preveiw-video (not virus)](https://youtu.be/wtl8gSeFA-c)

### CODE REVIEW

**Review by Gapraomoosap — APPROVED** [review]
image

**Comment by tonkaew131** [comment]
Why should error message blink?

**Comment by MonitorIizard** [comment]
> Why should error message blink?

To let the user know that the new input password is still wrong.

**Comment by tonkaew131** [comment]
How about remove error message when user started typing again

and if error occurs just show again

**Comment by MonitorIizard** [comment]
> How about remove error message when user started typing again
> 
> and if error occurs just show again

That sound good.

**Review by tonkaew131 — APPROVED** [review]

**Pull request merged**
